services:
  - type: cron
    name: crypto-signal-hourly
    env: python
    plan: starter
    schedule: "0 * * * *"  # roda todo hora no minuto 0 (UTC)
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python run_signal.py"
    envVars:
      - key: TELEGRAM_TOKEN
        value: "seu_token"
      - key: TELEGRAM_CHAT_ID
        value: "seu_chat_id"
